name: Fetch latest anti-bot scripts

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '5 * * * *' # Run every hour
  workflow_dispatch:

jobs:
  run:
    name: Fetch latest anti-bot scripts
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run fetch script
      run: ./fetch.sh
    - name: Commit changes if files have changed
      id: commit
      uses: EndBug/add-and-commit@v7
      with:
        message: "Updated scripts"
        add: "scripts/*"
    - name: Page deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4
      with:
        branch: gh-pages
        folder: scripts